In [28]:
import numpy as np
import pandas as pd
import pathlib
import os
from decimal import *

probabilitie =  pd.read_csv('./prob_08.csv', header=None)
table = pd.read_csv('./table_08.csv', header=None)


length= 20

In [29]:
def unconditional_probability(cipher_text):
	df_table = table
	df_prob = probabilitie
	
	probability = 0.0

	for plain_text_index in range(length):
		for key_text_index in range(length):
			if (df_table[plain_text_index][key_text_index] == cipher_text):
				probability += df_prob[plain_text_index][0] * df_prob[key_text_index][1]
	
	return probability

df_cipher_texts_unconditional_prob =  np.array([unconditional_probability(i) for i in range(length)])

In [30]:
def common_probability(cipher_text, plain_text):
	df_table = table
	df_prob = probabilitie
	
	probability = 0.0

	for key_index in range(length):
		if (df_table[plain_text][key_index] == cipher_text):
			probability += df_prob[plain_text][0] * df_prob[key_index][1]
	
	return probability

df_cipher_texts_common_prob =  np.array([[common_probability(i, j) for j in range(length)] for i in range(length)])

In [31]:
def conditional_probability():
    return np.array([
			[df_cipher_texts_common_prob[i][j] / df_cipher_texts_unconditional_prob[i] for j in range(length)
		] for i in range(length)])

df_cipher_texts_conditional_prob =  conditional_probability()

In [32]:
pd.DataFrame(df_cipher_texts_conditional_prob)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.000000,0.000000,0.000000,0.040000,0.080000,0.040000,0.040000,0.040000,0.040000,0.080000,0.040000,0.000000,0.080000,0.240000,0.160000,0.000000,0.040000,0.080000,0.000000,0.000000
1,0.000000,0.000000,0.488889,0.044444,0.044444,0.066667,0.000000,0.133333,0.000000,0.022222,0.088889,0.000000,0.022222,0.000000,0.000000,0.044444,0.022222,0.022222,0.000000,0.000000
2,0.115789,0.694737,0.000000,0.000000,0.000000,0.010526,0.021053,0.021053,0.000000,0.021053,0.000000,0.000000,0.021053,0.042105,0.010526,0.010526,0.010526,0.000000,0.021053,0.000000
3,0.776471,0.000000,0.000000,0.000000,0.023529,0.023529,0.023529,0.023529,0.011765,0.011765,0.000000,0.023529,0.011765,0.000000,0.011765,0.000000,0.023529,0.011765,0.011765,0.011765
4,0.400000,0.200000,0.000000,0.018182,0.000000,0.000000,0.145455,0.018182,0.000000,0.000000,0.000000,0.018182,0.054545,0.036364,0.000000,0.018182,0.018182,0.018182,0.018182,0.036364
5,0.000000,0.000000,0.000000,0.280000,0.040000,0.000000,0.120000,0.000000,0.080000,0.040000,0.040000,0.040000,0.040000,0.040000,0.120000,0.040000,0.040000,0.040000,0.040000,0.000000
6,0.338462,0.169231,0.169231,0.000000,0.015385,0.092308,0.000000,0.030769,0.000000,0.015385,0.000000,0.061538,0.015385,0.000000,0.000000,0.030769,0.030769,0.000000,0.015385,0.015385
7,0.000000,0.000000,0.000000,0.040000,0.120000,0.080000,0.000000,0.000000,0.040000,0.280000,0.040000,0.040000,0.040000,0.000000,0.040000,0.080000,0.040000,0.000000,0.000000,0.160000
8,0.000000,0.314286,0.000000,0.028571,0.028571,0.028571,0.057143,0.000000,0.000000,0.000000,0.028571,0.000000,0.000000,0.085714,0.085714,0.000000,0.200000,0.057143,0.028571,0.057143
9,0.169231,0.338462,0.169231,0.000000,0.107692,0.030769,0.000000,0.015385,0.000000,0.000000,0.000000,0.015385,0.015385,0.000000,0.000000,0.030769,0.030769,0.030769,0.015385,0.030769
10,0.146667,0.146667,0.440000,0.013333,0.000000,0.013333,0.026667,0.026667,0.013333,0.026667,0.000000,0.013333,0.013333,0.000000,0.000000,0.000000,0.013333,0.093333,0.000000,0.013333
11,0.169231,0.338462,0.169231,0.015385,0.000000,0.015385,0.015385,0.015385,0.107692,0.000000,0.000000,0.000000,0.015385,0.046154,0.061538,0.000000,0.000000,0.000000,0.030769,0.000000
12,0.115789,0.347368,0.347368,0.021053,0.010526,0.010526,0.000000,0.000000,0.010526,0.000000,0.063158,0.010526,0.000000,0.010526,0.000000,0.000000,0.010526,0.021053,0.021053,0.000000
13,0.000000,0.000000,0.000000,0.040000,0.040000,0.000000,0.000000,0.000000,0.040000,0.080000,0.200000,0.000000,0.040000,0.000000,0.000000,0.280000,0.040000,0.080000,0.040000,0.120000
14,0.440000,0.146667,0.146667,0.000000,0.000000,0.013333,0.000000,0.013333,0.026667,0.026667,0.000000,0.013333,0.013333,0.026667,0.000000,0.026667,0.000000,0.000000,0.013333,0.093333
15,0.488889,0.000000,0.000000,0.022222,0.044444,0.022222,0.000000,0.044444,0.044444,0.022222,0.066667,0.022222,0.022222,0.000000,0.000000,0.000000,0.000000,0.044444,0.133333,0.022222
16,0.169231,0.338462,0.169231,0.030769,0.015385,0.030769,0.000000,0.000000,0.030769,0.000000,0.015385,0.030769,0.107692,0.015385,0.015385,0.000000,0.000000,0.015385,0.015385,0.000000
17,0.209524,0.000000,0.628571,0.000000,0.000000,0.000000,0.019048,0.019048,0.019048,0.009524,0.009524,0.009524,0.000000,0.009524,0.000000,0.019048,0.009524,0.000000,0.028571,0.009524
18,0.129412,0.517647,0.129412,0.011765,0.011765,0.000000,0.011765,0.011765,0.011765,0.023529,0.011765,0.011765,0.000000,0.000000,0.082353,0.035294,0.000000,0.000000,0.000000,0.000000
19,0.115789,0.115789,0.578947,0.031579,0.000000,0.000000,0.010526,0.010526,0.010526,0.000000,0.000000,0.073684,0.000000,0.010526,0.000000,0.000000,0.021053,0.010526,0.010526,0.000000

In [33]:
def bayes_decision_function(cipher_text):
	return np.argmax(df_cipher_texts_conditional_prob[cipher_text])

df_bayes_decision_function =  [bayes_decision_function(i) for i in range(length)]

In [34]:
pd.DataFrame({ 'C': range(length), 'M': df_bayes_decision_function }).transpose()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
C,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
M,13,2,1,0,0,3,0,9,1,1,2,1,1,15,0,0,1,2,1,2

In [35]:
def bayes_function_losses(cipher_text, plain_text):
	return 0 if df_bayes_decision_function[cipher_text] == plain_text else 1

def bayes_function_average_losses():
	return sum(
		[bayes_function_losses(i, j) * df_cipher_texts_common_prob[i][j] for j in range(length) for i in range(length)]
	)

df_bayes_function_average_losses =  bayes_function_average_losses()

In [36]:

print(df_bayes_function_average_losses)

0.529600000000002

In [37]:
def stochastic_decision_function():
	matrix = np.zeros((length, length))

	for i in range(length):
		current_probability_set = df_cipher_texts_conditional_prob[i]

		max_probability = max(current_probability_set)
		max_probability_entrance = list(current_probability_set).count(max(current_probability_set))

		for j in range(length):
			matrix[i][j] = 1 / max_probability_entrance if current_probability_set[j] == max_probability else 0

	return matrix

df_stochastic_decision_function = stochastic_decision_function()

In [38]:
pd.DataFrame(df_stochastic_decision_function)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.5,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
14,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
def get_stochastic_function_losses(cipher_text, plain_text):
	return sum([df_stochastic_decision_function[cipher_text][i] for i in range(length) if i != plain_text])

def get_stochastic_function_average_losses():
	return sum(
		[get_stochastic_function_losses(i, j) * df_cipher_texts_common_prob[i][j] for j in range(length) for i in range(length)]
	)

df_stochastic_function_average_losses = get_stochastic_function_average_losses()

In [40]:

print(df_stochastic_function_average_losses)

0.529600000000002